### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Novemser** [Novemser/iTongJi-App#4]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.aitongji/com.example.aitongji.Home.MainActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2187)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
    at android.app.ActivityThread.access$800(ActivityThread.java:138)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5024)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at com.example.aitongji.Home.Home_Recycler_Adapter.<init>(Home_Recycler_Adapter.java:83)
    at com.example.aitongji.Home.HomePageCards.onCreateView(HomePageCards.java:60)
    at android.app.Fragment.performCreateView(Fragment.java:1700)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
    at android.app.BackStackRecord.run(BackStackRecord.java:684)
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
    at android.app.Activity.performStart(Activity.java:5240)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
    ... 11 more
java.lang.NullPointerException
    at com.example.aitongji.Home.Home_Recycler_Adapter.<init>(Home_Recycler_Adapter.java:83)
    at com.example.aitongji.Home.HomePageCards.onCreateView(HomePageCards.java:60)
    at android.app.Fragment.performCreateView(Fragment.java:1700)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
    at android.app.BackStackRecord.run(BackStackRecord.java:684)
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
    at android.app.Activity.performStart(Activity.java:5240)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
    at android.app.ActivityThread.access$800(ActivityThread.java:138)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5024)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by atenjin** [comment]
看起来还是从网络获取数据异常然后没有好好处理空指针问题
最近有点忙，过久再细看
我只是先提个建议：
不要信任从网络上返回的任何值，所以对网络的返回值一定要判空，
不然很容易发生这种基础的空指针异常
最好的方法是在网络层上就做一层防护
！=null才进success，然在success用上 @Nonnull 注解
==null和其他异常情况一样都进入fail中就会少很多麻烦

**Comment by Novemser** [comment]
原来可以用@Nonnull 0-0

感谢学长指教！O(∩_∩)O
